"""Compatibility export surface for solver types.

This module keeps the existing import path stable while separating the actual
type definitions into shared, schema, and runtime modules.
"""

from toolsv2.solver_common import (
    ActiveGridState,
    AdjacencyFinder,
    Attributes,
    BandId,
    CandidateEligibility,
    CardinalDirection,
    EdgeScope,
    EdgeTraversalMode,
    EntryContext,
    FrontierContext,
    GeometryBuildFeasibility,
    Junction,
    LogicalXRail,
    LogicalXRailId,
    LogicalYRail,
    LogicalYRailId,
    NeighborRelation,
    NodeDomain,
    NodeId,
    ObjectRef,
    PortEdgeId,
    PortId,
    PortRef,
    RenderProfileKey,
    RouteRequirement,
    RouteRequirementSchemaView,
    RoutingPolicy,
    ScalarValue,
    YRailBandState,
    YRailKind,
)
from toolsv2.solver_runtime import (
    build_runtime_junctions_for_active_grid,
    Endpoint,
    is_edge_id_usable,
    is_object_ref_active,
    is_port_ref_usable,
    Port,
    PortEdge,
    PortGraphIndex,
    PortGraphState,
    RuntimeJunction,
    RuntimeNode,
    RuntimeObjectSet,
)
from toolsv2.solver_schema import JunctionDefinition, NodeDefinition, PortDefinition, RenderProfileRef


__all__ = [
    "ActiveGridState",
    "AdjacencyFinder",
    "Attributes",
    "BandId",
    "build_runtime_junctions_for_active_grid",
    "CandidateEligibility",
    "CardinalDirection",
    "EdgeScope",
    "EdgeTraversalMode",
    "Endpoint",
    "EntryContext",
    "FrontierContext",
    "GeometryBuildFeasibility",
    "Junction",
    "JunctionDefinition",
    "LogicalXRail",
    "LogicalXRailId",
    "LogicalYRail",
    "LogicalYRailId",
    "NeighborRelation",
    "is_edge_id_usable",
    "is_object_ref_active",
    "is_port_ref_usable",
    "NodeDefinition",
    "NodeDomain",
    "NodeId",
    "ObjectRef",
    "Port",
    "PortDefinition",
    "PortEdge",
    "PortEdgeId",
    "PortGraphIndex",
    "PortGraphState",
    "PortId",
    "PortRef",
    "RenderProfileKey",
    "RenderProfileRef",
    "RouteRequirement",
    "RouteRequirementSchemaView",
    "RoutingPolicy",
    "RuntimeJunction",
    "RuntimeNode",
    "RuntimeObjectSet",
    "ScalarValue",
    "YRailBandState",
    "YRailKind",
]
